server:
  port: 8091
  max-http-form-post-size: 1048576
spring:
  application:
    name: clinic-tooth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://47.95.213.112:3306/tooth?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    # 下面为Druid连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    druid:
      initial-size: 5
      minIdle: 5
      maxActive: 20
    # 配置获取连接等待超时的时间
      max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis-plus:
  mapper-url: com.clinic.provider.mapper
  type-aliases-package: com.clinic.provider.domain       # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml       # mapper映射文件
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level:
    com.example.gradle.mapper: debug

#启用swagger2
swagger2:
  enable: true

#下划线转驼峰
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true

#自定义配置内容
real:
  path: D:/fils/


